the endpoint that returns the public data of an organization is devel…
alkemyTech/OT299-server pull request #21
Opened 2022-09-19 19:19 UTC by angelamonsalvep

…oped.

2022-09-19 21:27 UTC, paoliellolucas requested changes

2022-09-19 21:27 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/getways/DefaultOrganizationGateway.java
> +        return new Organization(organizationEntity.getId(),
usemos el builder de Lombok en lugar del constructor con todos los atributos, ya que es error-prone. 
Con el builder queda mucho mejor!

2022-09-19 21:27 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/exceptions/ResourceNotFoundException.java
> +@ResponseStatus(value = HttpStatus.NOT_FOUND)
esto al ser puramente de la capa web, no debería ser parte del domain. 
Por tal razón, creemos una clase GlobalExceptionHandler en el paquete web.
```
@ControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {

    @ExceptionHandler(ResourceNotFoundException.class)
    protected ResponseEntity<Object> handleConflict(
            RuntimeException ex, WebRequest request) {
        return handleExceptionInternal(ex, ex.getMessage(),
                new HttpHeaders(), HttpStatus.NOT_FOUND, request);
    }
}

2022-09-19 21:27 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/organizations/OrganizationsController.java
> +    OrganizationService organizationService;
private final que sean las dependencias

2022-09-19 21:27 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/organizations/OrganizationsController.java
> +        return new OrganizationDto(organization.getName(),
en este caso tmb, usemos el builder de Lombok en lugar del constructor con todos los params

2022-09-20 01:28 UTC, angelamonsalvep commented
The requested corrections were made.

2022-09-20 18:42 UTC, paoliellolucas approved these changes

2022-09-20 18:42 UTC, merged