Create endpoint delete user
alkemyTech/OT299-server pull request #42
Opened 2022-09-26 20:09 UTC by LindaCristal

2022-09-26 22:10 UTC, paoliellolucas requested changes

2022-09-26 22:10 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultUserGateway.java
> +        User user = toModel(repository.findById(id).orElseThrow(() ->
no es necesario pasarlo a model. Ya con el entity nos sirve para obtener el id.
userEntity = repository.findById().orElse...
repo.deleteById(entity.getId());

2022-09-26 23:31 UTC, LindaCristal commented on src/main/java/com/alkemy/ong/data/gateways/DefaultUserGateway.java
> +        User user = toModel(repository.findById(id).orElseThrow(() ->
Resuelto, muchas gracias

2022-09-27 17:00 UTC, paoliellolucas approved these changes

2022-09-27 17:00 UTC, merged