Endpoint authentication
alkemyTech/OT299-server pull request #51
Opened 2022-09-28 17:23 UTC by LindaCristal

2022-09-29 22:00 UTC, paoliellolucas requested changes

2022-09-29 22:00 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultUserGateway.java
> +        BCryptPasswordEncoder bCryptPasswordEncoder = new BCryptPasswordEncoder();
En lugar de hacer new del encoder, lo podríamos manejar como bean en la configuración de spring e inyectarlo aca como hacemos con el repo.

2022-09-30 20:44 UTC, LindaCristal commented on src/main/java/com/alkemy/ong/domain/users/UserService.java
> +    public boolean authentication(String email, String password) throws Exception {
Renombrados

2022-09-30 20:44 UTC, LindaCristal commented on src/main/java/com/alkemy/ong/web/UserController.java
> +    @PostMapping()
Parentesis borrados

2022-09-30 20:45 UTC, LindaCristal commented on src/main/java/com/alkemy/ong/web/AuthenticationController.java
> +        private String email;
Se agraga annotation @NotNull

2022-09-30 20:46 UTC, LindaCristal commented on src/main/java/com/alkemy/ong/data/gateways/DefaultUserGateway.java
> +        UserEntity entity = repository.findByEmail(email);
Se cambia a Optional y se utiliza orElseThrow()

2022-10-04 21:15 UTC, paoliellolucas approved these changes

2022-10-04 21:19 UTC, merged